/**
 * @nexusgen/types
 * Shared TypeScript types for NexusGen AI platform
 */

// Queue types
export {
  QueueName,
  QUEUE_CONFIGS,
  isProjectJobData,
  isGenerationJobData,
  isBuildJobData,
  isDeployJobData,
  isAITaskJobData,
  isNotificationJobData,
} from './queue';

export type {
  QueueConfiguration,
  ProjectAction,
  ProjectJobData,
  ProjectJobResult,
  GenerationConfig,
  GenerationType,
  GenerationJobData,
  GeneratedFile,
  GenerationJobResult,
  BuildJobData,
  BuildJobResult,
  DeploymentEnvironment,
  DeployJobData,
  DeployJobResult,
  AITaskType,
  AITaskJobData,
  AITaskJobResult,
  NotificationType,
  NotificationJobData,
  NotificationJobResult,
  JobStatus,
  JobMetadata,
  QueueStats,
  JobEventType,
  JobEvent,
} from './queue';

// User types
export type {
  UserRole,
  SubscriptionTier,
  UserStatus,
  User,
  UserProfile,
  UserPreferences,
  UserSession,
  UserCredentials,
  UserRegistration,
  ApiKey,
  UserUsageStats,
  Team,
  TeamMember,
  TeamInvitation,
} from './user';

// Project types
export type {
  ProjectVisibility,
  ProjectStatus,
  DeploymentStatus,
  FrameworkType,
  Project,
  ProjectDetails,
  ProjectSettings,
  ProjectEnvironment,
  EnvironmentVariable,
  ProjectCollaborator,
  Deployment,
  DeploymentSource,
  BuildConfig,
  ProjectAnalytics,
  PageAnalytics,
  CountryAnalytics,
  ProjectTemplate,
  Domain,
  SSLCertificate,
  DNSRecord,
  Webhook,
  WebhookEvent,
} from './project';

// Agent types
export type {
  AgentType,
  AgentStatus,
  MessageRole,
  ContentType,
  ModelProvider,
  Message,
  MessageContent,
  CodeBlock,
  ImageContent,
  FileContent,
  ToolCall,
  ToolResult,
  MessageMetadata,
  TokenUsage,
  AgentConfig,
  ModelConfig,
  ToolDefinition,
  ToolParameters,
  ToolParameterProperty,
  AgentConstraints,
  AgentCapabilities,
  Conversation,
  ConversationContext,
  FileReference,
  CodeSelection,
  EnvironmentInfo,
  AgentTask,
  TaskStep,
  TaskResult,
  Artifact,
  AgentError,
  StreamEventType,
  StreamEvent,
  StreamEventData,
} from './agent';

// API types
export type {
  ApiResponse,
  ApiError,
  ResponseMeta,
  RateLimitInfo,
  PaginationParams,
  PaginatedResponse,
  SortParams,
  FilterParams,
  // Auth
  LoginRequest,
  LoginResponse,
  RegisterRequest,
  RegisterResponse,
  RefreshTokenRequest,
  RefreshTokenResponse,
  PasswordResetRequest,
  PasswordResetConfirm,
  OAuthCallbackRequest,
  // User
  UpdateUserRequest,
  GetUserResponse,
  UpdateUserResponse,
  ListUsersResponse,
  CreateApiKeyRequest,
  CreateApiKeyResponse,
  // Project
  CreateProjectRequest,
  CreateProjectResponse,
  UpdateProjectRequest,
  UpdateProjectResponse,
  GetProjectResponse,
  ListProjectsResponse,
  ListTemplatesResponse,
  // Deployment
  CreateDeploymentRequest,
  CreateDeploymentResponse,
  GetDeploymentResponse,
  ListDeploymentsResponse,
  DeploymentLogsRequest,
  DeploymentLogsResponse,
  LogEntry,
  // Domain
  AddDomainRequest,
  AddDomainResponse,
  VerifyDomainResponse,
  // Webhook
  CreateWebhookRequest,
  CreateWebhookResponse,
  // Team
  CreateTeamRequest,
  CreateTeamResponse,
  UpdateTeamRequest,
  InviteMemberRequest,
  InviteMemberResponse,
  ListTeamMembersResponse,
  // Agent
  CreateConversationRequest,
  CreateConversationResponse,
  SendMessageRequest,
  MessageAttachment,
  SendMessageResponse,
  StreamMessageResponse,
  GetConversationResponse,
  ListConversationsResponse,
  GetAgentConfigResponse,
  ListAgentConfigsResponse,
  CreateTaskRequest,
  CreateTaskResponse,
  GetTaskResponse,
  // Health
  HealthCheckResponse,
  ServiceHealth,
  ApiUsageStats,
} from './api';
